Search results
MiriamAparicio/daw_m12_final_project_frontend-BAP pull request #11
Opened 2019-11-20 21:15 UTC by xavixanxe

SearchResults page components: 
-ResultsList
-ResultsItem
-ResultsFilter
-ServiceType

**Added react-rating package**

Fixed home wide and responsiveness and improved other pages behavior.

2019-11-20 21:34 UTC, franlol approved these changes
gj!

2019-11-20 21:34 UTC, franlol commented on src/views/Anuncis/components/ResultsFilter/ResultsFilter.js
> +                        </div>
Aquests 4 divs que fan el mateix, poder els podries extreure en 1 component

2019-11-21 09:15 UTC, MiriamAparicio requested changes

2019-11-21 09:15 UTC, MiriamAparicio commented on src/views/Anuncis/components/ResultsFilter/ResultsFilter.js
> +                        </div>
+1

2019-11-21 09:15 UTC, MiriamAparicio commented on src/views/Anuncis/components/ResultsFilter/ResultsFilter.js
> +                        </div>
Estem creant functional components barrejats amb class componets, hauria estat bé, ja que vam començar amb class components, continuar igual.
No cal que ho canviïs, però aquest mateix amb els propsTypes podria haver estat un class component.

2019-11-21 09:15 UTC, MiriamAparicio commented on src/views/Anuncis/components/ResultsList/ResultsList.js
> +}
En aquest class component els propTypes poden anar dins de la class, mira altres components i seguim una mica el mateix per consistència.

2019-11-21 09:15 UTC, MiriamAparicio commented on src/views/Anuncis/components/ResultsSearch/ResultsSearch.js
> +ResultsSearch.propTypes = {
De fet encara que sigui functional podem posar els propTypes a dins, no?
Millor veure els props a l'inici que haver de baixar fins al final del fitxer per veure'ls

2019-11-21 11:25 UTC, MiriamAparicio approved these changes

2019-11-21 12:24 UTC, merged