#137 - Post comments
MiriamAparicio/daw_m12_final_project_frontend-BAP pull request #23
Opened 2019-12-26 19:55 UTC by franlol

Adding Comments to make appointments.
This Pull request merges the following tasks:

* #137 - 'Implementació visualització comentaris usuari'
* #134 - 'Implementació formulari afegir missatge'

2019-12-27 07:29 UTC, MiriamAparicio requested changes

2019-12-27 07:29 UTC, MiriamAparicio commented on src/views/Profile/containers/ProfileComments/ProfileComments.js
> +  const url = 'http://localhost:3000/posts/messages/'
Si fins ara hem fet servir axios, i hem creat un fitxers de serveis per fer les crides als endpoint hauriem de fer el mateix per consitència.

2019-12-28 09:27 UTC, xavixanxe commented on src/views/Profile/containers/ProfileComments/ProfileComments.js
> +    return messages.map((message, index) => <Comment key={index} message={message} />);
Segons el que vam parlar, faltaria filtrar els missatges segons l'usuari que els va a visualitzar, si és l'owner els ha de veure tots i, si no, només els que ha escrit ell

2020-01-01 17:20 UTC, franlol commented on src/views/Profile/containers/ProfileComments/ProfileComments.js
> +  const url = 'http://localhost:3000/posts/messages/'
Fet :ok_hand:

2020-01-01 17:21 UTC, merged